// <auto-generated />
using API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250217104736_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Latest model smartphone with 128GB storage.",
                            ImageUrl = "smartphone.jpg",
                            Name = "Smartphone",
                            Price = 499.99m,
                            Stock = 500,
                            isActive = true
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-performance laptop for gaming and development.",
                            ImageUrl = "laptop.jpg",
                            Name = "Laptop",
                            Price = 1200.50m,
                            Stock = 150,
                            isActive = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "Noise-canceling wireless earbuds with long battery life.",
                            ImageUrl = "wireless_earbuds.jpg",
                            Name = "Wireless Earbuds",
                            Price = 99.99m,
                            Stock = 2000,
                            isActive = true
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stylish smart watch with fitness tracking features.",
                            ImageUrl = "smart_watch.jpg",
                            Name = "Smart Watch",
                            Price = 199.99m,
                            Stock = 850,
                            isActive = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "Ergonomic gaming chair for long hours of comfort.",
                            ImageUrl = "gaming_chair.jpg",
                            Name = "Gaming Chair",
                            Price = 299.99m,
                            Stock = 120,
                            isActive = false
                        },
                        new
                        {
                            Id = 6,
                            Description = "Portable bluetooth speaker with great sound quality.",
                            ImageUrl = "bluetooth_speaker.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 59.99m,
                            Stock = 1500,
                            isActive = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
